#ifdef _MSC_VER // fix visual studio intellisense errors
int
PORTA, PORTB, PORTC, PORTD, PINA0, PINA1, PINA2, PINA3, PINA4, PINA5,
PINA6, PINA7, PINA8, PINB0, PINB1, PINB2, PINB3, PINB4, PINB5, PINB6,
PINB7, PINB8, PINC0, PINC1, PINC2, PINC3, PINC4, PINC5, PINC6, PINC7,
PINC8, PIND0, PIND1, PIND2, PIND3, PIND4, PIND5, PIND6, PIND7, PIND8;
#undef showScreenLCD
void showScreenLCD(char* a, char* b);
#endif